# -*- coding: utf-8 -*-
"""MarcelaCampos_PGY1121_006V.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qb6eLoPvsp0ECaD6Qm56AARDnZHpkMSK
"""

import numpy as np

class Departamento:
    def __init__(self, numero):
        self.numero = numero
        self.comprador = None

    def esta_disponible(self):
        return self.comprador is None

    def asignar_comprador(self, comprador):
        self.comprador = comprador

matrizdepto = np.empty((10, 4), dtype=object)
departamento = 0
for f in range(10):
    for c in range(4):
        departamento = departamento + 1
        matrizdepto[f, c] = Departamento(departamento)

def mostrar_departamentos_disponibles():
    print("Disponibilidad de departamentos:")
    print()
    for f in range(10):
        for c in range(4):
            departamento = matrizdepto[f, c]
            estado = 'Disponible' if departamento.esta_disponible() else 'Vendido'
            print(f"Piso {10-f}, Tipo {c+1}: Departamento {departamento.numero} ({estado})")
        print()

def menu_principal():
    print("Bienvenido a Inmobiliaria CASA FELIZ")
    print()

    while True:
        print("1. Comprar departamento")
        print("2. Mostrar departamentos disponibles")
        print("3. Ver Listado de Compradores")
        print("4. Mostrar ventas totales")
        print("5. Salir")

        opcion = input("Seleccione una opción (1-5): ")
        print()

        if opcion == "1":
            comprar_departamento()
        elif opcion == "2":
            mostrar_departamentos_disponibles()
        elif opcion == "3":
            ver_listado_compradores()
        elif opcion == "4":
            mostrar_ventas_totales()
        elif opcion == "5":
            mostrar_mensaje_salida()
            break
        else:
            print("Opción inválida. Por favor, seleccione una opción válida.")
        print()

def comprar_departamento():
    while True:
        try:
            departamento = int(input("Indique el número de departamento que desea comprar: "))
            if departamento < 1 or departamento > 40:
                print("Número de departamento inválido. Por favor, seleccione un número válido.")
                continue
            fila = (departamento - 1) // 4
            columna = (departamento - 1) % 4
            if not matrizdepto[fila, columna].esta_disponible():
                print("El departamento seleccionado ya ha sido vendido. Por favor, seleccione otro.")
                continue
            run = input("Ingrese el RUN del comprador: ")
            nombre = input("Ingrese el nombre del comprador: ")
            apellido = input("Ingrese el apellido del comprador: ")
            comprador = Comprador(run, nombre, apellido)
            matrizdepto[fila, columna].asignar_comprador(comprador)
            print("¡Departamento comprado con éxito!")
            break
        except ValueError:
            print("Valor ingresado inválido. Por favor, ingrese un valor numérico válido para el departamento.")

def mostrar_mensaje_salida():
    print("¡Muchas gracias por visitar Inmobiliaria Casa Feliz!")
    print("Vuelva pronto.")

menu_principal()